services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file: .env #ADD where you are putting config file | EXAMPLE: /srv/dockerdata/homepage/config/.env
    ports:
      - 3000:3000
    volumes:
      - /srv/dockerdata/homepage/config:/app/config # Make sure your local config directory exists | CHANGE THIS IF DIRECTORY IS DIFFERENT | MUST BE THE SAME DIRECTORY YOU DOWNLOADED REPOSITORY TO
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    environment:
      HOMEPAGE_ALLOWED_HOSTS: 192.168.1.XXX:3000 # ADDRESS FOR HOMEPAGE | EXAMPLE: 192.168.1.XXX:3000 or homepage.myhomedomain.com See gethomepage.dev/installation/#homepage_allowed_hosts

    restart: unless-stopped
